# Generated by Django 5.2.8 on 2025-11-27 00:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('capacity', models.IntegerField()),
                ('available_hours', models.CharField(help_text='Dostupné hodiny aktivity, napr. 7:30-16:00.', max_length=200)),
                ('color', models.CharField(default='#778899', help_text='Farba aktivity pre zobrazenie v kalendári(hex kód).', max_length=150)),
                ('category', models.CharField(max_length=100, null=True)),
                ('room', models.CharField(help_text='Miestnosť alebo miesto konania aktivity.', max_length=20)),
                ('role', models.ForeignKey(help_text='Rola, ktorá môže participovať na aktivite(napr ucitel nevidi ps5 rezervaciu a student nevidi rezervaciu triedy).', on_delete=django.db.models.deletion.CASCADE, to='accounts.role')),
            ],
        ),
        migrations.CreateModel(
            name='ActivitySlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.activity')),
                ('teacher', models.ForeignKey(help_text='Učiteľ priradený k slotu (hlavne kvoli konzultaciam, môže byť null).', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'Čaká sa'), ('cancelled', 'Zrušené'), ('approved', 'Schválené')], max_length=30)),
                ('activity_slot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.activityslot')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
