# Generated by Django 5.2.8 on 2026-01-03 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_activityslot_teacher_alter_reservation_note_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='image_key',
            field=models.CharField(default='default', help_text="určuje akú fotku ma frontend použiť pre zobrazenie aktivity napr: 'playstation', 'gym', 'hall', 'lesson', 'book' alebo 'default' ", max_length=50, null=True),
        ),
    ]
