# Generated by Django 5.2.8 on 2026-01-12 12:45

import api.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_activity_image_key'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='created_by',
            field=models.ForeignKey(blank=True, default=api.models.get_default_admin_user, help_text="Ucitel ktorý vytvoril aktivitu, (kôli filtrovanie pre 'moje aktivity') default je prvý pouzivatel v tabulke s role admin", null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
