# Generated by Django 5.2.8 on 2026-02-23 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_activity_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='image_key',
            field=models.CharField(default='default', help_text="určuje akú fotku ma frontend použiť pre zobrazenie aktivity napr: 'playstation', 'gym', 'hall', 'lesson', 'book', 'vr' alebo 'default' ", max_length=50, null=True),
        ),
    ]
