# Generated by Django 5.2.8 on 2025-11-30 22:14

import accounts.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='must_change_password',
            field=models.BooleanField(default=True, help_text='User must change password on first login.'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.ForeignKey(default=accounts.models.get_default_role, on_delete=django.db.models.deletion.CASCADE, to='accounts.role'),
        ),
    ]
