"""
Django settings for app project.

Generated by 'django-admin startproject' using Django 5.2.8.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os
from urllib.parse import urlparse
from dotenv import load_dotenv
from datetime import timedelta

load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv("SECRET_KEY_SETTINGS")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []

AUTH_USER_MODEL = 'accounts.User'

# REST Framework Configuration
# Every endpoint (except login) requires token validation
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        # All endpoints require authentication by default
        'accounts.permissions.IsAuthenticatedWithValidToken',
    ),
    'EXCEPTION_HANDLER': 'rest_framework.views.exception_handler',
    'UNAUTHENTICATED_USER': 'django.contrib.auth.models.AnonymousUser',
}

# JWT Token Configuration
# Tokens expire after 8 hours, must be validated on every request
SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(hours=8),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),
    'ROTATE_REFRESH_TOKENS': False,
    'BLACKLIST_AFTER_ROTATION': False,
    'UPDATE_LAST_LOGIN': True,
    
    'ALGORITHM': 'HS256',
    'SIGNING_KEY': SECRET_KEY,
    'VERIFYING_KEY': None,
    'AUDIENCE': None,
    'ISSUER': None,
    'JWK_URL': None,
    'LEEWAY': 0,
    
    'AUTH_HEADER_TYPES': ('Bearer',),
    'AUTH_HEADER_NAME': 'HTTP_AUTHORIZATION',
    'USER_ID_FIELD': 'id',
    'USER_ID_CLAIM': 'user_id',
    'USER_AUTHENTICATION_RULE': 'rest_framework_simplejwt.authentication.default_user_authentication_rule',
    
    'AUTH_TOKEN_CLASSES': ('rest_framework_simplejwt.tokens.AccessToken',),
    'TOKEN_TYPE_CLAIM': 'token_type',
    'TOKEN_USER_CLASS': 'rest_framework_simplejwt.models.TokenUser',
    
    'JTI_CLAIM': 'jti',
    
    'SLIDING_TOKEN_REFRESH_EXP_CLAIM': 'refresh_exp',
    'SLIDING_TOKEN_LIFETIME': timedelta(hours=8),
    'SLIDING_TOKEN_REFRESH_LIFETIME': timedelta(days=7),
}



# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    "api",
    "rest_framework",
    "corsheaders",
    "accounts.apps.AccountsConfig",
    "djoser",
    "django.contrib.sites",
    "anymail",
    "social_django",  # Microsoft OAuth2
]

SITE_ID = 1

DJOSER = {
    "LOGIN_FIELD": "email",
    "PASSWORD_RESET_CONFIRM_URL": "reset-password-confirm/?uid={uid}&token={token}",
    "SEND_ACTIVATION_EMAIL": False,
    "PASSWORD_RESET_CONFIRM_RETYPE": False,
    "PASSWORD_RESET_SHOW_EMAIL_NOT_FOUND": True,
    "DOMAIN": os.getenv("FRONTEND_DOMAIN", "localhost:5173"),
}


# Mailgun Email Configuration
EMAIL_BACKEND = "anymail.backends.mailgun.EmailBackend"
DEFAULT_FROM_EMAIL = os.getenv("MAILGUN_FROM_EMAIL", "KP | GearHub <postmaster@mail.simonszi.me>")

ANYMAIL = {
    "MAILGUN_API_KEY": os.getenv("MAILGUN_API_KEY"),
    "MAILGUN_SENDER_DOMAIN": os.getenv("MAILGUN_DOMAIN", "mail.simonszi.me"),
    "MAILGUN_API_URL": "https://api.eu.mailgun.net/v3",  # EU region
}



MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    "corsheaders.middleware.CorsMiddleware",
    "social_django.middleware.SocialAuthExceptionMiddleware",  # Microsoft OAuth2
]

ROOT_URLCONF = 'app.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'app.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASE_URL = os.getenv("DATABASE_URL")

if DATABASE_URL:
    result = urlparse(DATABASE_URL)

    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.postgresql",
            "NAME": result.path[1:],  
            "USER": result.username,
            "PASSWORD": result.password,
            "HOST": result.hostname,
            "PORT": result.port,
        }
    }
else:
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.sqlite3",
            "NAME": BASE_DIR / "db.sqlite3",
        }
    }



# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Europe/Bratislava'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# v production potom treba zmenit lebo kazda url moze posielat requesty a mozu sa leaknut data
CORS_ALLOW_ALL_ORIGINS = True


# ========================================
# Microsoft OAuth2 Configuration
# ========================================
AUTHENTICATION_BACKENDS = (
    'accounts.backends.EmailBackend',  # Login with email (Django admin + API)
    'social_core.backends.microsoft.MicrosoftOAuth2',  # Microsoft OAuth2
    'django.contrib.auth.backends.ModelBackend',  # Default Django auth (username)
)

# Microsoft OAuth2 Settings
SOCIAL_AUTH_MICROSOFT_OAUTH2_KEY = os.getenv("SOCIAL_AUTH_MICROSOFT_GRAPH_KEY", "")
SOCIAL_AUTH_MICROSOFT_OAUTH2_SECRET = os.getenv("SOCIAL_AUTH_MICROSOFT_GRAPH_SECRET", "")
SOCIAL_AUTH_MICROSOFT_OAUTH2_TENANT_ID = os.getenv("TENANT_ID", "common")

# Redirect URI - social-auth uses /complete/{backend-name}/
# No need to set REDIRECT_URI manually, it's auto-generated

# Scopes for Microsoft OAuth2
SOCIAL_AUTH_MICROSOFT_OAUTH2_SCOPE = [
    'openid',
    'email',
    'profile',
]

# Pipeline for user creation/authentication
SOCIAL_AUTH_PIPELINE = (
    'social_core.pipeline.social_auth.social_details',
    'social_core.pipeline.social_auth.social_uid',
    'social_core.pipeline.social_auth.auth_allowed',
    'social_core.pipeline.social_auth.social_user',
    'social_core.pipeline.user.get_username',
    'social_core.pipeline.user.create_user',
    'social_core.pipeline.social_auth.associate_user',
    'social_core.pipeline.social_auth.load_extra_data',
    'social_core.pipeline.user.user_details',
)

# Store tokens in session
SOCIAL_AUTH_MICROSOFT_OAUTH2_EXTRA_DATA = [
    ('refresh_token', 'refresh_token'),
    ('access_token', 'access_token'),
    ('expires_in', 'expires_in'),
]

# URL settings for social-auth
LOGIN_URL = '/api/accounts/microsoft/login/'
LOGIN_REDIRECT_URL = '/api/accounts/auth/success/'  # Redirect after successful login
LOGOUT_REDIRECT_URL = '/'


# ========================================
# Microsoft Graph API Configuration
# ========================================
# For Client Credentials flow (app-only access)
MS_GRAPH_TENANT_ID = os.getenv("TENANT_ID", "")
MS_GRAPH_CLIENT_ID = os.getenv("CLIENT_ID", "")
MS_GRAPH_CLIENT_SECRET = os.getenv("CLIENT_SECRET", "")
MS_GRAPH_SCOPE = os.getenv("GRAPH_SCOPE", "https://graph.microsoft.com/.default")
MS_GRAPH_ENDPOINT_USERS = os.getenv("GRAPH_ENDPOINT_USERS", "https://graph.microsoft.com/v1.0/users")
